name: CI/CD Pipeline

#on push -> run pipeline
on:
  push:
    branches: [ main ] #runs when pushed to main branch
  pull_request:
    branches: [ main ] #runs when someone makes a PR to main
  
jobs: #define different tasks pipeline will do
  test: #first job is called "test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest requests flask python-dotenv

      - name: Run tests
        run: |
          pytest


  build:
    needs: test #only build it tests pass
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push weather fetcher
        uses: docker/build-push-action@v2    # Changed from user: to uses:
        with:
          context: ./services/weather_fetcher
          file: ./services/weather_fetcher/Dockerfile.weather_fetcher  
          push: true
          tags: balmanzar883/weather-fetcher:latest

      - name: Build and push weather processor
        uses: docker/build-push-action@v2
        with:
          context: ./services/weather_processor
          file: ./services/weather_processor/Dockerfile.weather_processor
          push: true
          tags: balmanzar883/weather-processor:latest

      - name: Build and push api gateway
        uses: docker/build-push-action@v2
        with:
          context: ./services/api_gateway
          file: ./services/api_gateway/Dockerfile.api_gateway
          push: true
          tags: balmanzar883/api-gateway:latest